### ISSUE TITLE
LOCALE_PROVIDER

### ISSUE THREAD

**Issue by SergiyR2P** [NickTimosh/sql_practice#1]
Нікіта, вітаю
Дякую, тобі за твій експрес курс по SQL

Будь ласка, підкажи, що я роблю не так.
У тебе на відео немає такої штуки як   LOCALE_PROVIDER = 'libc'
Про що це каже, або на що слід звернути увагу?
Дякую! )) 

![Знімок екрана 2024-05-07 192920](https://github.com/NickTimosh/sql_practice/assets/169172483/86a9639a-9cc1-4c67-921d-7ed58e5af2c9)

**Comment by NickTimosh** [comment]
Дякую за відгук!!!
Думаю, у мене не видно цього через те, що це є налаштування за замовчуванням.
Тут можна дізнатися більше:
https://www.postgresql.org/docs/current/app-initdb.html#:~:text=The%20libc%20locale%20provider%20takes%20the%20locale%20settings,to%20set%20values%20for%20the%20individual%20locale%20categories.
